spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
#logging:
#  level:
#    com.project.apipractice.global.api : DEBUG

infra:
  job:
    key: ${API_KEY}

server:
  port: 8082

feign:
  client:
    config:
      default:
        logger-level: full
  circuitbreaker:
    enabled: true
